// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

import 'env.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final FirebaseOptions android = FirebaseOptions(
    apiKey: Env.apiKeyAndroid,
    appId: '1:915498031769:android:6fc25e4dbba064de77b608',
    messagingSenderId: '915498031769',
    projectId: 'fruit-hub-2a6b2',
    storageBucket: 'fruit-hub-2a6b2.firebasestorage.app',
  );

  static final FirebaseOptions ios = FirebaseOptions(
    apiKey: Env.apiKeyIos,
    appId: '1:915498031769:ios:9c74a7d5a270d5ee77b608',
    messagingSenderId: '915498031769',
    projectId: 'fruit-hub-2a6b2',
    storageBucket: 'fruit-hub-2a6b2.firebasestorage.app',
    androidClientId:
        '915498031769-8gi78mk4hkr6r7lblkkg1l91nejs5vfd.apps.googleusercontent.com',
    iosClientId:
        '915498031769-3b04gg2lnjmvr7jh3p9ngqqoq6vbdihh.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitHubDashboard',
  );
}
